### ISSUE TITLE
download link broken on xda

### ISSUE THREAD

**Issue by Wyyyned** [enesuzun2002/android_kernel_samsung_exynos7420#3]

**Comment by mustaqimM** [comment]
@enesuzun2002 I have the same problem, the two links from androidfilehost are down(it keeps no saying no mirrors found):

1. [Hyper-Kernel-G92X-P-Treble-v1.1.zip](https://androidfilehost.com/?fid=6006931924117896230)
2. [vendor-nx-9.0-20190201.zip](https://androidfilehost.com/?fid=6006931924117896206)
